### ISSUE TITLE
開発サーバー起動時、index.tsxにて起こるエラーについて

### ISSUE THREAD

**Issue by EdamAme-x** [yoidea/applied-math-alerm#5]
`yarn start`を利用して開発Serverを立ち上げ、indexページにアクセスすると

"Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.

See more info here: https://nextjs.org/docs/messages/react-hydration-error"

"Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering."

以上２つのエラーメッセージが表示される。

おそらく、HTMLの記法に沿っていない、もしくはHTML内のインデントがおかしく、レンダリング時の差異を検知したものと見られる。

**Comment by EdamAme-x** [comment]
以下は該当の部分

```tsx
     <div className={styles.home} style={isFlash ? {
        background: 'rgba(255, 255, 255, 0.7)'
      } : {}}>
        <p className={styles.text}>
          {`${time.getHours().toString().padStart(2,'0')}:${time.getMinutes().toString().padStart(2,'0')}`}
        </p>
        <button className={styles.button} onClick={handleClick}>
          停止
        </button>
      </div>
```

**Comment by yoidea** [comment]
自分の環境では`yarn build`時にType Errorは発生しますが、Unhandled Runtime Errorは`build`, `start`, ブラウザコンソールから確認できませんでした

**Comment by EdamAme-x** [comment]
あ、再現状況を間違えていました
正しくは yarn devです 申し訳ない
